=== localmatters/object-serializer/src/main/schema/serializations.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- This schema describes the structure of a lm-object-serializer configuration
     file. Such configuration file describes how different objects or models
     should be serialized. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  
           targetNamespace="http://www.localmatters.com/schema/serializations" 
           xmlns:ser="http://www.localmatters.com/schema/serializations"
           xmlns="http://www.localmatters.com/schema/serializations" 
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0.1">

    <!-- Serializations and direct children (which expects an ID) -->
    <xs:element name="serializations">
        <xs:annotation>
            <xs:documentation xml:lang="en-US">Configuration defining how to serialize objects and models</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="complex">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="complexType">
                                <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:extension>    
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="map">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="mapType">
                                <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:extension>    
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="list">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="listType">
                                <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:extension>    
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="value">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="valueType">
                                <xs:attribute name="id" type="xs:string" use="required"/>
                            </xs:extension>    
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
        
        <!-- constraints on the ID -->
        <xs:unique name="idKey">
            <xs:selector xpath=".//*"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        <xs:keyref name="parentRef" refer="idKey">
            <xs:selector xpath=".//ser:complex"/>
            <xs:field xpath="@parent"/>
        </xs:keyref>
        <xs:keyref name="targetRef" refer="idKey">
            <xs:selector xpath=".//ser:ref"/>
            <xs:field xpath="@target"/>
        </xs:keyref>

    </xs:element>

    
    <!-- Complex Tag type -->
    <xs:complexType name="complexType">
		<xs:sequence>
			<xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="attribute">
				    <xs:complexType>
				        <xs:attributeGroup ref="baseAttributesGroup"/>
				        <xs:attribute name="id" type="xs:string" use="optional"/>
				    </xs:complexType>
				</xs:element>
				<xs:group ref="baseElementsGroupOptionalId"/>
			</xs:choice>
		</xs:sequence>
        <xs:attributeGroup ref="baseAttributesGroup"/>
        <xs:attribute name="parent" type="xs:string" use="optional"/>
    </xs:complexType>
    
    
    <!-- Map Tag type -->
    <xs:complexType name="mapType">
        <xs:sequence>
            <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:group ref="baseElementsGroupOptionalId" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attributeGroup ref="baseAttributesGroup"/>
        <xs:attribute name="key" type="xs:string" use="optional"/>
    </xs:complexType>

    
    <!-- List Tag type -->
    <xs:complexType name="listType">
        <xs:sequence>
            <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:group ref="baseElementsGroupOptionalId" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attributeGroup ref="baseAttributesGroup"/>
    </xs:complexType>

    
    <!-- Value Tag type -->
    <xs:complexType name="valueType">
        <xs:attributeGroup ref="baseAttributesGroup"/>
    </xs:complexType>
    
    
    <!-- Ref Tag type -->
    <xs:complexType name="refType">
        <xs:attributeGroup ref="baseAttributesGroup"/>
        <xs:attribute name="target" type="xs:string" use="required"/>
    </xs:complexType>
    

    <!-- The base list of sub-elements with optional IDs -->
    <xs:group name="baseElementsGroupOptionalId">
        <xs:choice>
		    <xs:element name="complex">
                <xs:complexType>
                    <xs:complexContent>
			            <xs:extension base="complexType">
			                <xs:attribute name="id" type="xs:string" use="optional"/>
			            </xs:extension>    
    		        </xs:complexContent>
                </xs:complexType>
		    </xs:element>
		    <xs:element name="map">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="mapType">
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                        </xs:extension>    
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
		    <xs:element name="list">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="listType">
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                        </xs:extension>    
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
		    <xs:element name="value">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="valueType">
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                        </xs:extension>    
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
		    <xs:element name="ref" type="refType"/>
        </xs:choice>
    </xs:group>


    <!-- Base attributes -->
    <xs:attributeGroup name="baseAttributesGroup">
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="property" type="xs:string" use="optional"/>
        <xs:attribute name="bean" type="xs:string" use="optional"/>
        <xs:attribute name="constant" type="xs:string" use="optional"/>
        <xs:attribute name="display-empty" type="xs:boolean" use="optional" default="false"/>
    </xs:attributeGroup>
    
</xs:schema>

=== localmatters/object-serializer/src/test/resources/test-multiple-config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<serializations xmlns="http://schema.localmatters.org/serializations" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schema.localmatters.org/serializations http://schema.localmatters.org/serializations.xsd">

    <!-- org.localmatters.serializer.test.domain.ObjectWithGenerics -->
    <complex id="ObjectWithGenerics" bean="ObjectWithGenerics" name="ObjectWithGenerics">
        <list property="array"/>

        <!-- Unable to identify the types for the [list] iteration!
             The configuration of its elements must be written manually. -->
        <list property="list">
            <value name="element"/>
        </list>

        <!-- Iteration of [java.util.List<java.lang.String>] -->
        <list property="listOfListOfString">
            <list name="element"/>
        </list>

        <!-- Iteration of [java.util.Map<java.lang.String, java.util.List>] -->
        <list property="listOfMapOfStringAndList">

            <!-- map of [class java.lang.String] and [interface java.util.List] -->
            <map name="listOfMapOfStringAnd">

                <!-- Unable to identify the types for the [entry] iteration!
                     The configuration of its elements must be written manually. -->
                <list>
                    <value name="element"/>
                </list>
            </map>
        </list>

        <!-- Iteration of [class org.localmatters.serializer.test.domain.ParameterizedObject] -->
        <list property="listOfParameterizedObject">
            <list name="element"/>
        </list>
        <list property="listOfString"/>

        <!-- Configured the complex map returned by [map] as a list.
             This can change to a <map> by setting its [key] attribute to the
             property of the key object that identifies it. -->
        <list property="map">
            <complex name="entry">

                <!-- Unable to resolve the class for the element [key]!
                     Its configuration must be written manually. -->
                <value property="key"/>

                <!-- Unable to resolve the class for the element [value]!
                     Its configuration must be written manually. -->
                <value property="value"/>
            </complex>
        </list>
        <map property="mapOfStringAndDouble"/>
    </complex>

    <!-- org.localmatters.serializer.test.domain.DummyObject -->
    <complex id="org.localmatters.serializer.test.domain.DummyObject" bean="DummyObject" name="DummyObject">

        <!-- map of [class java.lang.String] and [class org.localmatters.serializer.test.domain.DummyObject$Address] -->
        <map property="addresses">
            <ref target="Address"/>
        </map>

        <!-- Unable to identify the types for the [addressesRaw] map!
             The configuration of its entries must be written manually. -->
        <map property="addressesRaw"/>
        <value property="id"/>
        <value property="name"/>
        <list property="orders"/>

        <!-- Configured the complex map returned by [ordersByAddresses] as a list.
             This can change to a <map> by setting its [key] attribute to the
             property of the key object that identifies it. -->
        <list property="ordersByAddresses">
            <complex name="ordersByAddress">
                <ref property="key" target="Address"/>
                <list property="value"/>
            </complex>
        </list>
        <list property="ordersList"/>
    </complex>

    <!-- org.localmatters.serializer.test.domain.extra.DummyObject -->
    <complex id="DummyObject" bean="DummyObject" name="DummyObject">
        <ref property="dummy" target="org.localmatters.serializer.test.domain.DummyObject"/>
    </complex>

    <!-- org.localmatters.serializer.test.domain.ChildOfSelfreferencingObject -->
    <complex id="ChildOfSelfreferencingObject" bean="ChildOfSelfreferencingObject" name="ChildOfSelfreferencingObject">
        <value property="name"/>

        <!-- Iteration of [class org.localmatters.serializer.test.domain.SelfReferencingObject] -->
        <list property="others">
            <ref name="other" target="SelfReferencingObject"/>
        </list>
    </complex>

    <!-- org.localmatters.serializer.test.domain.SelfReferencingObject -->
    <complex id="SelfReferencingObject" name="SelfReferencingObject">
        <value property="name"/>

        <!-- Iteration of [class org.localmatters.serializer.test.domain.SelfReferencingObject] -->
        <list property="others">
            <ref name="other" target="SelfReferencingObject"/>
        </list>
    </complex>

    <!-- org.localmatters.serializer.test.domain.DummyObject$Address -->
    <complex id="Address" name="Address">
        <value property="city"/>
        <value property="state"/>
        <value property="street"/>
        <value property="z"/>
        <value property="zip"/>
    </complex>
</serializations>
